
export const macaronFlavors = [
  {
    id: 1,
    name: "Gourmet White Chocolate Raspberry Macarons - Fresh & Artisanal",
    price: 300,
    category: "Specialty Flavors",
    options: [
      { box: 6, price: 1800 },
      { box: 10, price: 3000 },
      { box: 20, price: 5400, discount: "10%" },
    ],
    image: "images/white-chocolate-raspberry.jpg",
    alt: "Handcrafted white chocolate raspberry macaron with a creamy ganache and tart berry filling",
    description: "A delicate macaron with a sweet white chocolate ganache and a tart raspberry filling.",
    ingredients: "Almond flour, icing sugar, egg whites, white chocolate, raspberries, cream.",
    allergies: "Contains nuts (almonds) and dairy.",
  },
  {
    id: 2,
    name: "Decadent Peanut Paste Snickers Macarons - Nutty Delight",
    price: 300,
    category: "Specialty Flavors",
    options: [
      { box: 6, price: 1800 },
      { box: 10, price: 3000 },
      { box: 20, price: 5400 },
    ],
    image: "images/milk-chocolate-peanut.jpg",
    alt: "Rich milk chocolate and peanut macaron featuring a surprise Snickers piece inside",
    description: "A rich and nutty macaron with a smooth milk chocolate and peanut paste filling, with a surprise of a piece of Snickers inside.",
    ingredients: "Almond flour, icing sugar, egg whites, milk chocolate, peanuts, cream, Snickers bar.",
    allergies: "Contains nuts (almonds, peanuts) and dairy.",
  },
  {
    id: 3,
    name: "Premium Pistachio Macarons - Authentic French Style",
    price: 350,
    category: "Classic Flavors",
    options: [
      { box: 10, price: 3500 },
      { box: 30, price: 9450, discount: "10%" },
    ],
    image: "images/pistachio.jpg",
    alt: "Classic French pistachio macaron filled with authentic, rich pistachio ganache",
    description: "A classic macaron with a flavorful pistachio ganache, made from real pistachios.",
    ingredients: "Almond flour, icing sugar, egg whites, pistachios, white chocolate, cream.",
    allergies: "Contains nuts (almonds, pistachios) and dairy.",
  },
  {
    id: 4,
    name: "Zesty Lemon & Lemon Gel Macarons - Refreshing Citrus",
    price: 300,
    category: "Classic Flavors",
    options: [
      { box: 6, price: 1800 },
      { box: 10, price: 3000 },
      { box: 20, price: 5400, discount: "10%" },
    ],
    image: "images/lemon-ganache.jpg",
    alt: "Bright and tangy lemon macaron with a white chocolate ganache and zesty gel center",
    description: "A zesty and refreshing macaron with a lemon-infused white chocolate ganache and a tangy lemon gel center.",
    ingredients: "Almond flour, icing sugar, egg whites, white chocolate, lemon, cream.",
    allergies: "Contains nuts (almonds) and dairy.",
  },
  {
    id: 5,
    name: "Rich Coffee & Salted Caramel Macarons - Espresso Infused",
    price: 300,
    category: "Classic Flavors",
    options: [
      { box: 6, price: 1800 },
      { box: 10, price: 3000 },
      { box: 20, price: 5400, discount: "10%" },
    ],
    image: "images/coffee-caramel.jpg",
    alt: "Coffee-infused macaron with a smooth dark chocolate ganache and gooey caramel core",
    description: "A perfect pairing of rich coffee-infused ganache and a sweet, gooey caramel center.",
    ingredients: "Almond flour, icing sugar, egg whites, dark chocolate, coffee, sugar, cream.",
    allergies: "Contains nuts (almonds) and dairy.",
  },
  {
    id: 6,
    name: "Custom-Made Macarons - Personalized Event Catering",
    price: 350,
    category: "Custom & Gifts",
    minimum: 30,
    options: [{ box: 30, price: 9450, discount: "10%" }],
    image: "images/custom-made.jpg",
    alt: "Beautifully customized macarons in various colors and designs for special occasions",
    description: "Create your own unique macaron! Choose your colors and flavors for a truly personalized treat. Perfect for events and special occasions.",
    ingredients: "Varies based on customization. Please inquire for details.",
    allergies: "May contain nuts and dairy. Please specify any allergies when ordering.",
  },
  {
    id: 7,
    name: "Assorted Macaron Gift Box - Variety Flavor Pack",
    category: "Custom & Gifts",
    minimum: "30 pieces for 3 flavors",
    options: [{ box: 30, price: 8100, discount: "10%" }],
    image: "images/assorted-flavors.jpg",
    alt: "A vibrant collection of assorted gourmet macarons in a gift-ready presentation",
    description: "A delightful assortment of our most popular flavors. A perfect choice when you can't decide on just one!.",
    ingredients: "Varies. Please see individual macaron descriptions.",
    allergies: "Contains nuts (almonds) and dairy.",
  },
  {
    id: 8,
    name: "Vegan Macarons - Plant-Based & Dairy-Free Treats",
    price: 400,
    category: "Vegan",
    options: [
      { box: 6, price: 2400 },
      { box: 10, price: 4000 },
      { box: 20, price: 7200, discount: "10%" },
    ],
    image: "images/vegan.png",
    alt: "Delicious plant-based vegan macarons made with aquafaba and natural ingredients",
    description: "A delicious and cruelty-free macaron, made with plant-based ingredients.",
    ingredients: "Almond flour, icing sugar, aquafaba, vegan butter, and natural flavors.",
    allergies: "Contains nuts (almonds).",
  },
];
