
export const initialMacarons = [
  {
    name: 'Rose Lychee',
    description: 'A delicate floral macaron with a sweet lychee filling.',
    price: 3.50,
    image: '/images/macaron-1.png',
    color: '#FADADD',
    options: [{ box: 6, price: 20 }, { box: 12, price: 38 }, { box: 24, price: 72 }],
  },
  {
    name: 'Pistachio',
    description: 'A classic macaron with a rich and nutty pistachio ganache.',
    price: 3.25,
    image: '/images/macaron-2.png',
    color: '#D4E6C3',
    options: [{ box: 6, price: 18 }, { box: 12, price: 35 }, { box: 24, price: 68 }],
  },
  {
    name: 'Salted Caramel',
    description: 'A perfect balance of sweet and salty with a gooey caramel center.',
    price: 3.50,
    image: '/images/macaron-3.png',
    color: '#E0A96D',
    options: [{ box: 6, price: 20 }, { box: 12, price: 38 }, { box: 24, price: 72 }],
  },
  {
    name: 'Lavender Honey',
    description: 'A unique and aromatic macaron with a hint of honey.',
    price: 3.75,
    image: '/images/macaron-4.png',
    color: '#E1D5E7',
    options: [{ box: 6, price: 21 }, { box: 12, price: 40 }, { box: 24, price: 75 }],
  },
  {
    name: 'Chocolate Hazelnut',
    description: 'A decadent macaron filled with creamy chocolate hazelnut spread.',
    price: 3.50,
    image: '/images/macaron-5.png',
    color: '#C1A48E',
    options: [{ box: 6, price: 20 }, { box: 12, price: 38 }, { box: 24, price: 72 }],
  },
  {
    name: 'Mango Passionfruit',
    description: 'An exotic and tangy macaron with a tropical fruit filling.',
    price: 3.75,
    image: '/images/macaron-6.png',
    color: '#FFD580',
    options: [{ box: 6, price: 21 }, { box: 12, price: 40 }, { box: 24, price: 75 }],
  },
   {
    name: 'Earl Grey',
    description: 'A sophisticated macaron infused with the flavor of Earl Grey tea.',
    price: 3.50,
    image: '/images/macaron-7.png',
    color: '#BDB1A6',
    options: [{ box: 6, price: 20 }, { box: 12, price: 38 }, { box: 24, price: 72 }],
  },
];
